<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="adminpage1.aspx.cs" Inherits="librarymanagementproject.adminpage1" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">


    <center>
        <p style="margin-left: 40px">
        <br />
        </p>
        <p align="right">
            <asp:Button ID="btn_logout" runat="server" OnClick="btn_logout_Click" Text="log_out" />
        </p>
        <asp:Label ID="lbl_userdata" runat="server" Text="USER DATA" Font-Size="XX-Large" BorderStyle="Groove" ForeColor="Lime" BorderColor="Black"></asp:Label>
        <br />
        <br />
        <asp:GridView ID="gv_user" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderColor="Black" BorderStyle="Solid" CellPadding="1" DataKeyNames="user_id" OnRowCancelingEdit="GridView1_RowCancelingEdit" OnRowDeleting="GridView1_RowDeleting" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" CellSpacing="10">
            <Columns>
                <asp:BoundField DataField="user_id" HeaderText="User ID" SortExpression="user_id" />
                <asp:BoundField DataField="f_name" HeaderText="First name" SortExpression="f_name" />
                <asp:BoundField DataField="l_name" HeaderText="Last name" SortExpression="l_name" />
                <asp:BoundField DataField="email" HeaderText="E-Mail" SortExpression="email" />
                <asp:BoundField DataField="phone_no" HeaderText="Phoneno" SortExpression="phone_no" />
                <asp:BoundField DataField="password" HeaderText="password" SortExpression="password" />
            </Columns>
        </asp:GridView>
        <br />
        <asp:Label ID="lbl_userinsert" runat="server" Text="USER DATA INSERT" Font-Size="XX-Large" BorderStyle="Groove" ForeColor="Lime" BorderColor="Black"></asp:Label>
        <br />
        <br />
        <table style="width: 100%;">
            <tr>
                <td class="auto-style1">
                    <asp:Label ID="lbl_fname" runat="server" Text="First Name"></asp:Label>
                </td>
                <td class="auto-style2">
                    <asp:TextBox ID="txt_fname" runat="server" Width="530px"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="rfv_fn" runat="server" ControlToValidate="txt_fname" ErrorMessage="Please fill the first name" ForeColor="Red" ValidationGroup="a"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:Label ID="lbl_lname" runat="server" Text="Last Name"></asp:Label>
                </td>
                <td class="auto-style2">
                    <asp:TextBox ID="txt_lname" runat="server" Width="530px"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="rfv_ln" runat="server" ControlToValidate="txt_lname" ErrorMessage="Please enter the last name" ForeColor="Red" ValidationGroup="a"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:Label ID="lbl_email" runat="server" Text="Email"></asp:Label>
                </td>
                <td class="auto-style2">
                    <asp:TextBox ID="txt1_emial" runat="server" Width="530px"></asp:TextBox>
                </td>
                <td>
                    <asp:RegularExpressionValidator ID="rev_emial" runat="server" ControlToValidate="txt1_emial" ErrorMessage="Enter valid email" ForeColor="Red" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*" ValidationGroup="a"></asp:RegularExpressionValidator>
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:Label ID="lbl_PHno" runat="server" Text="Phone no"></asp:Label>
                </td>
                <td class="auto-style2">
                    <asp:TextBox ID="txt_pno" runat="server" Width="530px"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="rfv_pno" runat="server" ControlToValidate="txt_pno" ErrorMessage="Enter the Phone no" ForeColor="Red" ValidationGroup="a"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:Label ID="lbl_pswd" runat="server" Text="Password"></asp:Label>
                </td>
                <td class="auto-style2">
                    <asp:TextBox ID="txt_pswd" runat="server" Width="530px"></asp:TextBox>
                </td>
                <td>
                    <asp:RequiredFieldValidator ID="rfv_pswd" runat="server" ControlToValidate="txt_pswd" ErrorMessage="Enter the password" ForeColor="Red" ValidationGroup="a"></asp:RequiredFieldValidator>
                </td>
            </tr>
            <tr>
                <td class="auto-style1">
                    <asp:Label ID="lbl_cpswd" runat="server" Text="Confirm Password"></asp:Label>
                </td>
                <td class="auto-style2">
                    <asp:TextBox ID="txtc_pswd" runat="server" Width="530px"></asp:TextBox>
                </td>
                <td>
                    <asp:CompareValidator ID="cv_cpswd" runat="server" ControlToCompare="txt_pswd" ControlToValidate="txtc_pswd" ErrorMessage="password is not same" ForeColor="Red" ValidationGroup="a"></asp:CompareValidator>
                </td>
            </tr>
        </table>

        <br />
        <br />
        <asp:Button ID="btn_reset" runat="server" OnClick="btn_reset_Click" Text="Reset" />
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <asp:Button ID="btn_submit" runat="server" OnClick="btn_submit_Click" Text="submit" ValidationGroup="a" />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
    </center>

</asp:Content>
