<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Category.aspx.cs" Inherits="librarymanagementproject.Category" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

   <center>

       <br />
       <asp:Label ID="lbl_categorydata" runat="server" BorderColor="Black" BorderStyle="Groove" ForeColor="Lime" Text="CATEGORY DATA" Font-Size="Large"></asp:Label>
       <br />
       <br />
       <asp:GridView ID="gv_category" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="cat_id" OnRowCancelingEdit="gv_category_RowCancelingEdit" OnRowDeleting="gv_category_RowDeleting" OnRowEditing="gv_category_RowEditing" OnRowUpdating="gv_category_RowUpdating">
           <Columns>
               <asp:BoundField DataField="cat_id" HeaderText="Category-ID" SortExpression="cat_id" />
               <asp:BoundField DataField="category_name" HeaderText="category Name" SortExpression="category_name" />
           </Columns>
       </asp:GridView>

       <br />
       <asp:Label ID="lbl_categoryinsert" runat="server" BorderColor="Black" BorderStyle="Groove" ForeColor="Lime" Text="CATEGORY INSERT" Font-Size="X-Large"></asp:Label>

       <br />
       <br />
       <table style="width:100%;">
           <tr>
               <td style="height: 20px">
                   <asp:Label ID="lbl_categoryname" runat="server" Text="Category Name"></asp:Label>
               </td>
               <td style="height: 20px">
                   <asp:TextBox ID="txt_category_name" runat="server" Width="530px"></asp:TextBox>
               </td>
               <td style="height: 20px">
                   <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="txt_category_name" ErrorMessage="Please enter the Category name" ForeColor="Red" ValidationGroup="a"></asp:RequiredFieldValidator>
               </td>
           </tr>
           <tr>
               <td colspan="3"><center>

                               <asp:Button ID="btn_reset" runat="server"  Text="Reset" OnClick="btn_reset_Click" />

                               &nbsp;
                               <asp:Button ID="btn_submit" runat="server" OnClick="btn_submit_Click" Text="Submit" ValidationGroup="a" />

                               </center>&nbsp;</td>
           </tr>
       </table>

   </center>

</asp:Content>
